# Tema 3: Representaciones clásicas

## Ejercicio 1: Bolsa de Palabras

### Apartado a

In [1]:
from sklearn.feature_extraction.text import CountVectorizer


# Corpus de ejemplo
corpus = [
    "Estamos a finales de febrero.",
    "En febrero sigue haciendo frío.",
    "Esto es una frase de ejemplo que habla de un mes del año.",
]

# Crear el modelo de bolsa de palabras con bigramas
vectorizer = CountVectorizer(ngram_range=(2, 2))
matrix = vectorizer.fit_transform(corpus)

# Mostrar los nombres de las características y la matriz documento-término
print("Feature Names:", vectorizer.get_feature_names_out())
print("Document-Term Matrix:\n", matrix.toarray())


Feature Names: ['de ejemplo' 'de febrero' 'de un' 'del año' 'ejemplo que' 'en febrero'
 'es una' 'estamos finales' 'esto es' 'febrero sigue' 'finales de'
 'frase de' 'habla de' 'haciendo frío' 'mes del' 'que habla'
 'sigue haciendo' 'un mes' 'una frase']
Document-Term Matrix:
 [[0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0]
 [1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 1]]


In [2]:
# Corpus de ejemplo
corpus = [
    "Estamos a finales de febrero.",
    "En febrero sigue haciendo frío.",
    "Esto es una frase de ejemplo que habla de un mes del año.",
]

# Crear el modelo de bolsa de palabras con bigramas
vectorizer = CountVectorizer(ngram_range=(1, 3))
matrix = vectorizer.fit_transform(corpus)

# Mostrar los nombres de las características y la matriz documento-término
print("Feature Names:", vectorizer.get_feature_names_out())
print("Document-Term Matrix:\n", matrix.toarray())

Feature Names: ['año' 'de' 'de ejemplo' 'de ejemplo que' 'de febrero' 'de un' 'de un mes'
 'del' 'del año' 'ejemplo' 'ejemplo que' 'ejemplo que habla' 'en'
 'en febrero' 'en febrero sigue' 'es' 'es una' 'es una frase' 'estamos'
 'estamos finales' 'estamos finales de' 'esto' 'esto es' 'esto es una'
 'febrero' 'febrero sigue' 'febrero sigue haciendo' 'finales' 'finales de'
 'finales de febrero' 'frase' 'frase de' 'frase de ejemplo' 'frío' 'habla'
 'habla de' 'habla de un' 'haciendo' 'haciendo frío' 'mes' 'mes del'
 'mes del año' 'que' 'que habla' 'que habla de' 'sigue' 'sigue haciendo'
 'sigue haciendo frío' 'un' 'un mes' 'un mes del' 'una' 'una frase'
 'una frase de']
Document-Term Matrix:
 [[0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0
  0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [1 2 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1
 

### Apartado b

In [3]:
# Documentos de ejemplo
docs = ["The cat jumped cat", "The white tiger roared", "Bird flying in the sky"]

# Crear un objeto CountVectorizer con representacion binaria
vectorizer = CountVectorizer(binary=True)

# Usar el método fit_transform para transformar los documentos en una matriz binaria
binary = vectorizer.fit_transform(docs)

# Mostrar el vocabulario (características) de la matriz binaria
print(vectorizer.get_feature_names_out())

# Mostrar la matriz binaria
print(binary.toarray())

['bird' 'cat' 'flying' 'in' 'jumped' 'roared' 'sky' 'the' 'tiger' 'white']
[[0 1 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 1 0 0]]


In [4]:
# Documentos de ejemplo
docs = ["The cat jumped cat", "The white tiger roared", "Bird flying in the sky"]

# Crear un objeto CountVectorizer con frecuencias por termino
vectorizer = CountVectorizer()

# Usar el método fit_transform para transformar los documentos en una matriz frecuencias
frequencies = vectorizer.fit_transform(docs)

# Mostrar el vocabulario (características) de la matriz frecuencias
print(vectorizer.get_feature_names_out())

# Mostrar la matriz frecuencias
print(frequencies.toarray())

['bird' 'cat' 'flying' 'in' 'jumped' 'roared' 'sky' 'the' 'tiger' 'white']
[[0 2 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 1 0 0]]


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer


# Documentos de ejemplo
docs = ["The cat jumped cat", "The white tiger roared", "Bird flying in the sky"]

# Crear un objeto TfidfVectorizer
vectorizer = TfidfVectorizer()

# Usar el método fit_transform para transformar los documentos en una matriz TF-IDF
tfidf = vectorizer.fit_transform(docs)

# Mostrar el vocabulario (características) de la matriz TF-IDF
print(vectorizer.get_feature_names_out())

# Mostrar la matriz TF-IDF
print(tfidf.toarray())

['bird' 'cat' 'flying' 'in' 'jumped' 'roared' 'sky' 'the' 'tiger' 'white']
[[0.         0.86477018 0.         0.         0.43238509 0.
  0.         0.2553736  0.         0.        ]
 [0.         0.         0.         0.         0.         0.54645401
  0.         0.32274454 0.54645401 0.54645401]
 [0.47952794 0.         0.47952794 0.47952794 0.         0.
  0.47952794 0.28321692 0.         0.        ]]


## Ejercicio 2: Matriz de coocurrencias

In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import defaultdict, Counter
import numpy as np
import pandas as pd


# Descargar recursos de NLTK
nltk.download("punkt")
nltk.download("stopwords")

### Apartado a

In [7]:
# Texto de ejemplo
text = "Mysterious tunnels sketched by Leonardo da Vinci in the late 1400s may have been found at the Castle. Secret tunnels at the Sforza Castle."
text

'Mysterious tunnels sketched by Leonardo da Vinci in the late 1400s may have been found at the Castle. Secret tunnels at the Sforza Castle.'

In [8]:
# Se preprocesa el texto, eliminando stopwords, convirtiendo las palabras a minúsculas, tokenizando y eliminando los tokens no alfanuméricos
stop_words = set(stopwords.words("english"))
words = word_tokenize(text.lower())
words = [word for word in words if word.isalnum() and word not in stop_words]

In [9]:
# Se define el tamaño de ventana y se crea la lista de pares que coocurren dentro de la ventana

# Definir el tamaño de ventana para la coocurrencia
window_size = 2

# Crear una lista de pares de palabras que coocurren
co_occurrences = defaultdict(Counter)
for i, word in enumerate(words):
    for j in range(max(0, i - window_size), min(len(words), i + window_size + 1)):
        if i != j:
            co_occurrences[word][words[j]] += 1

In [10]:
# Se obtiene el vocabulario
# Crear una lista de palabras únicas
unique_words = list(set(words))

In [11]:
# Se crea la matriz de coocurrencia
# Inicializar la matriz de coocurrencias
co_matrix = np.zeros((len(unique_words), len(unique_words)), dtype=int)

# Poblar la matriz de coocurrencias
word_index = {word: idx for idx, word in enumerate(unique_words)}
for word, neighbors in co_occurrences.items():
    for neighbor, count in neighbors.items():
        co_matrix[word_index[word]][word_index[neighbor]] = count

In [12]:
# Se crea un DataFrame para una mejor visualización
# Crear un DataFrame para una mejor legibilidad
co_matrix_df = pd.DataFrame(co_matrix, index=unique_words, columns=unique_words)

# Mostrar la matriz de coocurrencias
co_matrix_df

found  1400s  leonardo  mysterious  vinci  castle  tunnels  \
found           0      1         0           0      0       1        0   
1400s           1      0         0           0      1       0        0   
leonardo        0      0         0           0      1       0        1   
mysterious      0      0         0           0      0       0        1   
vinci           0      1         1           0      0       0        0   
castle          1      0         0           0      0       0        2   
tunnels         0      0         1           1      0       2        0   
sforza          0      0         0           0      0       1        1   
late            0      1         0           0      1       0        0   
secret          1      0         0           0      0       1        1   
sketched        0      0         1           1      0       0        1   
da              0      0         1           0      1       0        0   
may             1      1         0           0      0       1        0   

            sforza  late  secret  sketched  da  may  
found            0     0       1         0   0    1  
1400s            0     1       0         0   0    1  
leonardo         0     0       0         1   1    0  
mysterious       0     0       0         1   0    0  
vinci            0     1       0         0   1    0  
castle           1     0       1         0   0    1  
tunnels          1     0       1         1   0    0  
sforza           0     0       1         0   0    0  
late             0     0       0         0   1    1  
secret           1     0       0         0   0    0  
sketched         0     0       0         0   1    0  
da               0     1       0         1   0    0  
may              0     1       0         0   0    0

### Apartado b

In [13]:
from sklearn.metrics.pairwise import cosine_similarity


def cosine_similarity_sklearn(matrix, word1_index, word2_index):
    # Obtener los vectores de las dos palabras
    vector1 = matrix[word1_index].reshape(1, -1)
    vector2 = matrix[word2_index].reshape(1, -1)

    # Calcular la similitud del coseno usando sklearn
    similarity = cosine_similarity(vector1, vector2)[0][0]

    return similarity


# Calcular la similitud del coseno entre las palabras "da" y "vinci" (índices 8 y 9)
similarity = cosine_similarity_sklearn(co_matrix, 8, 9)
print(f"La similitud del coseno entre las dos palabras es: {similarity}")

# Calcular la similitud del coseno entre las palabras "may" y "tunnels" (índices 0 y 4)
similarity = cosine_similarity_sklearn(co_matrix, 0, 4)
print(f"La similitud del coseno entre las dos palabras es: {similarity}")

# Calcular la similitud del coseno entre una palabra consigo misma (índices 4 y 4)
similarity = cosine_similarity_sklearn(co_matrix, 4, 4)
print(f"La similitud del coseno entre las dos palabras es: {similarity}")

# Calcular la similitud del coseno entre las palabras "tunnels" y "castle" (índices 4 y 12)
similarity = cosine_similarity_sklearn(co_matrix, 4, 12)
print(f"La similitud del coseno entre las dos palabras es: {similarity}")

# Calcular la similitud del coseno entre las palabras "secret" y "tunnels" (índices 2 y 4)
similarity = cosine_similarity_sklearn(co_matrix, 2, 4)
print(f"La similitud del coseno entre las dos palabras es: {similarity}")


La similitud del coseno entre las dos palabras es: 0.0
La similitud del coseno entre las dos palabras es: 0.25
La similitud del coseno entre las dos palabras es: 1.0
La similitud del coseno entre las dos palabras es: 0.5
La similitud del coseno entre las dos palabras es: 0.25


### Apartado c

In [14]:
def most_similar_words(matrix, word_index, n):
    # Obtener el vector de la palabra dada
    word_vector = matrix[word_index].reshape(1, -1)

    # Calcular la similitud del coseno entre la palabra dada y todas las demás palabras
    similarities = cosine_similarity(matrix, word_vector).flatten()

    # Obtener los índices de las n palabras más similares (excluyendo la palabra dada)
    most_similar_indices = similarities.argsort()[-n - 1 : -1][::-1]

    return most_similar_indices


n_words_most_similar = 5

# Obtener los índices de las 3 palabras más similares a la palabra en el índice que corresponda
word = "leonardo"
similar_words_indices = most_similar_words(co_matrix, 3, n_words_most_similar)
print("Las palabras más similares a ", word, " son: {similar_words_indices}")

for index in similar_words_indices:
    print(unique_words[index])


word = "da"
similar_words_indices = most_similar_words(co_matrix, 8, n_words_most_similar)
print("Las palabras más similares a ", word, " son: {similar_words_indices}")

for index in similar_words_indices:
    print(unique_words[index])

Las palabras más similares a  leonardo  son: {similar_words_indices}
leonardo
castle
sforza
da
sketched
Las palabras más similares a  da  son: {similar_words_indices}
leonardo
1400s
found
vinci
da


## Ejercicio 3: Latent Dirichlet Allocation

### Apartado a

In [15]:
from sklearn.decomposition import LatentDirichletAllocation 
from pathlib import Path
import warnings
import json

# Suprimimos warnings para mayor claridad
warnings.filterwarnings("ignore") 

In [16]:
# Construir ruta al archivo de datos
PATH_DATA = Path.cwd().parent / 'data'

# Lista de textos a procesar
with open(PATH_DATA / 'Noticias.json', encoding="utf8") as json_file:
    datos = json.load(json_file)

tuplas = list(
    zip(
        [noticia.get("Title") for noticia in datos],
        [noticia.get("TextContent") for noticia in datos],
    )
)
df = pd.DataFrame(tuplas, columns=["Titular", "Noticia"])
df

Titular  \
0   Suspendido el partido Villarreal-Espanyol por ...   
1   Reino Unido y otros países aliados de Ucrania ...   
2   Los premios Oscar dan la gloria al cine indie ...   
3   Emilia Pérez, Karla Sofía Gascón, Demi Moore y...   
4   La Aemet retira también el aviso rojo por fuer...   
5   España propone financiar la defensa de los paí...   
6   El tequila lubricó la gran noche en la que Hol...   
7   Trump congela toda la ayuda militar a Ucrania ...   
8   La Comunidad Valenciana y otras cinco regiones...   
9   Objetivo: acabar con la pesca fantasma y las r...   
10  Los científicos abandonan el sueño de crear ‘v...   
11  Valladolid ya no permite más terrazas cerradas...   

                                              Noticia  
0   El temporal de lluvia y nieve afecta a áreas d...  
1   Los países europeos de la OTAN y Canadá han de...  
2   ¿Qué premia exactamente Hollywood y su industr...  
3   Fue Beckett el que, en un arrebato no precisam...  
4   La Agencia Estatal de Meteorología (Aemet) ha ...  
5   España considera que la seguridad es un “Bien ...  
6   La bebida fluyó con abundancia en los cuatro n...  
7   El presidente estadounidense, Donald Trump, ha...  
8   Este martes seguirá arreciando en el este de l...  
9   Dos biólogos de la Universitat de València par...  
10  Aunque los laboratorios de biología sintética ...  
11  El Ayuntamiento espera ordenar este año la Pla...

In [17]:
# Lista de textos a procesar
documents = df["Noticia"].tolist()

# Configurar y crear el vectorizador
tf_vectorizer = CountVectorizer(
    stop_words=[],  # No eliminamos stopwords por ahora []
    min_df=1,  # Incluir palabras que aparecen al menos 1 vez
    max_df=1.0,  # Sin límite superior de frecuencia
    lowercase=True,  # Convertir todo a minúsculas
    max_features=50000,  # Máximo número de palabras a considerar
    token_pattern="[a-zA-Z0-9]{3,}",  # Palabras de 3+ caracteres
    analyzer="word",
)

# Crear la matriz de documentos-términos
bag_of_words = tf_vectorizer.fit_transform(documents)

# Obtener el vocabulario
dictionary = tf_vectorizer.get_feature_names_out()
vocabulary = tf_vectorizer.vocabulary_

print("Estadísticas del preprocesamiento:")
print(f"- Tamaño del vocabulario: {len(dictionary)} palabras únicas")
print(f"- Dimensiones de la matriz: {bag_of_words.shape}")

# Mostrar las palabras más frecuentes
word_freq = bag_of_words.sum(axis=0).A1
top_words_idx = word_freq.argsort()[-10:][::-1]
print("\nPalabras más frecuentes:")
for idx in top_words_idx:
    print(f"- {dictionary[idx]}: {word_freq[idx]} apariciones")

Estadísticas del preprocesamiento:
- Tamaño del vocabulario: 390 palabras únicas
- Dimensiones de la matriz: (12, 390)

Palabras más frecuentes:
- que: 15 apariciones
- los: 12 apariciones
- del: 9 apariciones
- para: 9 apariciones
- las: 8 apariciones
- una: 8 apariciones
- por: 8 apariciones
- con: 7 apariciones
- han: 6 apariciones
- este: 5 apariciones


**Entrenamiento LDA**

El algoritmo LDA tiene varios hiperparámetros importantes:

* n_topics: Número de tópicos a encontrar
    - Debe elegirse según el conocimiento del dominio
    - Se puede optimizar usando métricas como coherencia o perplejidad

* alpha: Prior de la distribución documentos-tópicos
    - alpha < 1: documentos se concentran en pocos tópicos
    - alpha > 1: documentos mezclan varios tópicos
    - alpha = 1: distribución uniforme

* beta: Prior de la distribución tópicos-palabras
    - beta < 1: tópicos más específicos (pocas palabras)
    - beta > 1: tópicos más generales (muchas palabras)
    - beta = 1: distribución uniforme





In [18]:
# Parámetros del modelo
n_topics = 2  # Número moderado de tópicos para empezar
alpha = 1.0  # Documentos algo especializados
beta = 0.1  # Tópicos bastante específicos

# Crear y entrenar el modelo
print("Configuración del modelo LDA:")
print(f"- Número de tópicos: {n_topics}")
print(f"- Alpha: {alpha}")
print(f"- Beta: {beta}")
print("\nIniciando entrenamiento...\n")

lda = LatentDirichletAllocation(
    n_components=n_topics,  # Número de tópicos
    doc_topic_prior=alpha,  # Prior documentos-tópicos
    topic_word_prior=beta,  # Prior tópicos-palabras
    max_iter=25,  # Máximo de iteraciones
    learning_method="online",  # Método de aprendizaje
    evaluate_every=1,  # Evaluar en cada iteración
    n_jobs=-1,  # Usar todos los cores
    random_state=0,  # Semilla para reproducibilidad
    verbose=1,  # Mostrar progreso
)

# Entrenar el modelo
lda.fit(bag_of_words)

Configuración del modelo LDA:
- Número de tópicos: 2
- Alpha: 1.0
- Beta: 0.1

Iniciando entrenamiento...



iteration: 1 of max_iter: 25, perplexity: 2758.9888
iteration: 2 of max_iter: 25, perplexity: 2360.5562
iteration: 3 of max_iter: 25, perplexity: 2063.0452
iteration: 4 of max_iter: 25, perplexity: 1844.5082
iteration: 5 of max_iter: 25, perplexity: 1679.1945
iteration: 6 of max_iter: 25, perplexity: 1550.3955
iteration: 7 of max_iter: 25, perplexity: 1447.6857
iteration: 8 of max_iter: 25, perplexity: 1364.3213
iteration: 9 of max_iter: 25, perplexity: 1295.7429
iteration: 10 of max_iter: 25, perplexity: 1238.7427
iteration: 11 of max_iter: 25, perplexity: 1190.9847
iteration: 12 of max_iter: 25, perplexity: 1150.7174
iteration: 13 of max_iter: 25, perplexity: 1116.5946
iteration: 14 of max_iter: 25, perplexity: 1087.5606
iteration: 15 of max_iter: 25, perplexity: 1062.7727
iteration: 16 of max_iter: 25, perplexity: 1041.5487
iteration: 17 of max_iter: 25, perplexity: 1023.3301
iteration: 18 of max_iter: 25, perplexity: 1007.6550
iteration: 19 of max_iter: 25, perplexity: 994.1387
ite

LatentDirichletAllocation(doc_topic_prior=1.0, evaluate_every=1,
                          learning_method='online', max_iter=25, n_components=2,
                          n_jobs=-1, random_state=0, topic_word_prior=0.1,
                          verbose=1)

**Análisis de Resultados**

Se analizan los resultados de tres formas diferentes:

* Palabras más relevantes por tópico
* Documentos más representativos de cada tópico
* Distribución de tópicos en documentos específicos



In [19]:
# Configuración de visualización
no_top_words = 10  # Número de palabras top por tópico
no_top_documents = 2  # Número de documentos top por tópico

# Obtener las distribuciones
doc_topics = lda.transform(bag_of_words)  # Distribución de tópicos por documento
topics = lda.components_  # Distribución de palabras por tópico


# 1. Detallar tópicos encontrados
print("TÓPICOS DESCUBIERTOS")
print("Cada tópico se representa por sus palabras más probables\n")

for topic_idx, topic in enumerate(topics):
    print(f" Tópico {topic_idx + 1}:")
    # Obtener índices de las palabras más probables
    top_words_idx = topic.argsort()[: -no_top_words - 1 : -1]
    top_words = [dictionary[i] for i in top_words_idx]
    top_probs = [topic[i] for i in top_words_idx]

    # Mostrar palabras y sus probabilidades

    for word, prob in zip(top_words, top_probs):
        print(f"   {word}: {prob:.4f}")
    print()


TÓPICOS DESCUBIERTOS
Cada tópico se representa por sus palabras más probables

 Tópico 1:
   que: 7.7820
   por: 5.1884
   los: 5.0778
   han: 5.0076
   las: 4.0323
   horas: 3.5345
   para: 3.0125
   rojo: 3.0002
   meteorolog: 2.4789
   provincia: 2.4727

 Tópico 2:
   del: 7.8142
   que: 6.8644
   los: 6.7025
   una: 6.0120
   para: 5.8943
   con: 4.9902
   este: 4.8988
   las: 3.9034
   ses: 3.0481
   verdad: 2.9999



In [20]:
# 2. Documentos más representativos por tópico
print("\n DOCUMENTOS MÁS REPRESENTATIVOS POR TÓPICO")
print("Se muestran los documentos que más peso tienen en cada tópico\n")

for topic_idx in range(n_topics):
    print(f" Tópico {topic_idx + 1}:")
    # Obtener los documentos más representativos
    top_doc_indices = np.argsort(doc_topics[:, topic_idx])[::-1][:no_top_documents]

    for doc_idx in top_doc_indices:
        title = df.iloc[doc_idx]["Titular"]
        weight = doc_topics[doc_idx, topic_idx]
        print(f"   '{title}'")
        print(f"      Peso: {weight:.4f}")
    print()


 DOCUMENTOS MÁS REPRESENTATIVOS POR TÓPICO
Se muestran los documentos que más peso tienen en cada tópico

 Tópico 1:
   'Suspendido el partido Villarreal-Espanyol por la emergencia meteorológica.'
      Peso: 0.9846
   'La Aemet retira también el aviso rojo por fuertes lluvias en Castellón, que se mantiene en naranja.'
      Peso: 0.9734

 Tópico 2:
   'Los premios Oscar dan la gloria al cine indie y castigan una vez más a Netflix'
      Peso: 0.9871
   'Reino Unido y otros países aliados de Ucrania se comprometen a rearmar a Zelenski: 'Botas en el terreno y aviones en los cielos''
      Peso: 0.9814



In [21]:
# Para mostrar matriz documento-tópico
# pd.set_option('display.max_columns', None)

topicnames = ["topic" + str(x) for x in range(0, lda.n_components)]
norm_doc_topics = []
for i in doc_topics:
    norm_doc_topics.append(["{0:.3f}".format(weight) for weight in i])

df = pd.DataFrame(norm_doc_topics, columns=topicnames, index=df["Titular"].tolist())

df

topic0 topic1
Suspendido el partido Villarreal-Espanyol por l...  0.985  0.015
Reino Unido y otros países aliados de Ucrania s...  0.019  0.981
Los premios Oscar dan la gloria al cine indie y...  0.013  0.987
Emilia Pérez, Karla Sofía Gascón, Demi Moore y ...  0.022  0.978
La Aemet retira también el aviso rojo por fuert...  0.973  0.027
España propone financiar la defensa de los país...  0.965  0.035
El tequila lubricó la gran noche en la que Holl...  0.027  0.973
Trump congela toda la ayuda militar a Ucrania p...  0.961  0.039
La Comunidad Valenciana y otras cinco regiones,...  0.185  0.815
Objetivo: acabar con la pesca fantasma y las re...  0.056  0.944
Los científicos abandonan el sueño de crear ‘vi...  0.961  0.039
Valladolid ya no permite más terrazas cerradas ...  0.049  0.951

In [22]:
# Matriz tópico-palabra

# Matriz tema-palabra clave
df_topic_keywords = pd.DataFrame(
    lda.components_ / lda.components_.sum(axis=1)[:, np.newaxis]
)

# Asignar columnas e índice
df_topic_keywords.columns = dictionary
df_topic_keywords.index = topicnames

# Ver
df_topic_keywords.head()

000       100       106       143       180      2017      2024  \
topic0  0.000579  0.000582  0.004247  0.004189  0.004206  0.000553  0.000561   
topic1  0.002948  0.002939  0.000371  0.000400  0.000396  0.002947  0.002938   

             500  abundancia  academia  ...    vieron     viles     volod  \
topic0  0.004209    0.000569  0.000552  ...  0.004200  0.004228  0.004178   
topic1  0.000393    0.002929  0.002944  ...  0.000376  0.000394  0.000394   

        voluntad    willem      ximo      xito  zelenski     zonas  zorrilla  
topic0  0.004127  0.000543  0.004255  0.000539  0.004147  0.000572  0.000549  
topic1  0.000417  0.002958  0.000384  0.002931  0.000418  0.002920  0.002937  

[2 rows x 390 columns]

**Evaluación del modelo**

Utilizamos dos métricas principales:

1. Log Likelihood (mayor es mejor):
   * Indica cómo de bien el modelo explica los datos
   * Valores más altos indican mejor ajuste

2. Perplejidad (menor es mejor):
   * Mide qué tan "sorprendido" está el modelo por los datos
   * Valores más bajos indican mejor generalización



In [23]:
# Calcular métricas
log_likelihood = lda.score(bag_of_words)
perplexity = lda.perplexity(bag_of_words)

print("MÉTRICAS DE EVALUACIÓN")
print(f"- Log Likelihood: {log_likelihood:.2f}")
print(f"- Perplejidad: {perplexity:.2f}")

# Comparar con diferentes valores de hiperparámetros
print("\nCOMPARACIÓN DE HIPERPARÁMETROS")
print("Probando diferentes configuraciones para encontrar el mejor modelo...")

# Probar diferentes números de tópicos
n_topics_range = [2, 4, 6, 8]
results = []

for n_top in n_topics_range:
    model = LatentDirichletAllocation(
        n_components=n_top,
        doc_topic_prior=alpha,
        topic_word_prior=beta,
        max_iter=25,
        random_state=0,
    )
    model.fit(bag_of_words)

    results.append(
        {
            "n_topics": n_top,
            "perplexity": model.perplexity(bag_of_words),
            "log_likelihood": model.score(bag_of_words),
        }
    )

# Mostrar resultados
results_df = pd.DataFrame(results)
print("\nResultados con diferentes números de tópicos:")
print(results_df)

MÉTRICAS DE EVALUACIÓN
- Log Likelihood: -3732.99
- Perplejidad: 943.43

COMPARACIÓN DE HIPERPARÁMETROS
Probando diferentes configuraciones para encontrar el mejor modelo...

Resultados con diferentes números de tópicos:
   n_topics  perplexity  log_likelihood
0         2  878.213841    -3693.950115
1         4  801.510384    -3644.141370
2         6  775.912329    -3626.451547
3         8  865.176829    -3685.798982


### Apartado b

In [24]:
text = "Trump ordena suspender toda la ayuda militar de Estados Unidos a Ucrania tras su bronca a Zelenski."
vector = tf_vectorizer.transform([text])
topic_dist = lda.transform(vector)[0]

print(f"Texto analizado: '{text}'")
print("Distribución de tópicos:")

# Mostrar cada tópico con su probabilidad
for idx, prob in enumerate(topic_dist, 1):
    bar = "▓" * int(prob * 50)  # Barra visual simple
    print(f"Tópico {idx}: {prob:.2%} {bar}")

Texto analizado: 'Trump ordena suspender toda la ayuda militar de Estados Unidos a Ucrania tras su bronca a Zelenski.'
Distribución de tópicos:
Tópico 1: 78.78% ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
Tópico 2: 21.22% ▓▓▓▓▓▓▓▓▓▓
